###### Main Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-mainservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-main-deployment
  template:
    metadata:
      labels:
        name: acmeair-main-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-mainservice-java
        image: image-registry.openshift-image-registry.svc:5000/acmeair-g13/acmeair-mainservice-java:latest
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 9080
        - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-inmemory-agent
        - name: JAEGER_AGENT_PORT
          value: '6832'
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
        - name: ACCESS_LOGGING_ENABLED
          value: 'false'
        - name: TRACE_SPEC
          value: '*=info'
        - name: LOGGING_FORMAT
          value: 'simple'
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-main-service
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    name: acmeair-main-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-secure-main-service
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    name: acmeair-main-deployment
